//AUTO GENERATED BY index-web-components.js

import _0 from "./Root";
import _1 from "./roots/Load";
import _2 from "./roots/Error";
import _3 from "./roots/App";
import _4 from "./views/PageHeader";
import _5 from "./views/PageContent";
import _6 from "./views/AppRibbon";
import _7 from "./panels/Panel";
import _8 from "./panels/PagePanel";
import _9 from "./panels/DeckTreePanel";
import _10 from "./pages/DeckPage";
import _11 from "./atomic/TextButton";
import _12 from "./atomic/Spacer";
import _13 from "./atomic/RibbonItem";
import _14 from "./atomic/IconButton";
import _15 from "./atomic/DeckItem";
import _16 from "./atomic/Card";

export { _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16 };

declare global {
    interface HTMLElementTagNameMap {
        'root-component': _0;
        'load-root': _1;
        'error-root': _2;
        'app-root': _3;
        'page-header': _4;
        'page-content': _5;
        'app-ribbon': _6;
        'panel-element': _7;
        'page-panel': _8;
        'deck-tree-panel': _9;
        'deck-page': _10;
        'text-button': _11;
        'spacer-component': _12;
        'ribbon-item': _13;
        'icon-button': _14;
        'deck-item': _15;
        'card-element': _16;
    }
}