//AUTO GENERATED BY index-web-components.js

import _0 from "./Root";
import _1 from "./roots/Load";
import _2 from "./roots/Error";
import _3 from "./roots/App";
import _4 from "./views/TemplateEditor";
import _5 from "./views/PageHeader";
import _6 from "./views/PageContent";
import _7 from "./views/FlashcardGrid";
import _8 from "./views/ContextMenu";
import _9 from "./views/CardInputEditor";
import _10 from "./views/CardEditorHeader";
import _11 from "./views/AppRibbon";
import _12 from "./pages/TemplateOverviewPage";
import _13 from "./pages/TemplateEditorPage";
import _14 from "./pages/DeckPage";
import _15 from "./nodes/OutputNode";
import _16 from "./nodes/InputNode";
import _17 from "./panels/Panel";
import _18 from "./panels/PagePanel";
import _19 from "./panels/DeckTreePanel";
import _20 from "./modals/SettingsModal";
import _21 from "./modals/DebugModal";
import _22 from "./modals/CardCreatorModal";
import _23 from "./modals/BaseModal";
import _24 from "./atomic/TextButton";
import _25 from "./atomic/TemplateThumbnail";
import _26 from "./atomic/TemplateSelect";
import _27 from "./atomic/Spacer";
import _28 from "./atomic/RibbonItem";
import _29 from "./atomic/ModalContent";
import _30 from "./atomic/FlashcardThumbnail";
import _31 from "./atomic/DimmedBackground";
import _32 from "./atomic/CardInputFieldView";

export { _0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32 };

declare global {
    interface HTMLElementTagNameMap {
        'root-component': _0;
        'load-root': _1;
        'error-root': _2;
        'app-root': _3;
        'template-editor': _4;
        'page-header': _5;
        'page-content': _6;
        'flashcard-grid': _7;
        'context-menu': _8;
        'card-input-editor': _9;
        'card-editor-header': _10;
        'app-ribbon': _11;
        'template-overview-page': _12;
        'template-editor-page': _13;
        'deck-page': _14;
        'output-node': _15;
        'input-node': _16;
        'panel-element': _17;
        'page-panel': _18;
        'deck-tree-panel': _19;
        'settings-modal': _20;
        'debug-modal': _21;
        'card-creator': _22;
        'base-modal': _23;
        'text-button': _24;
        'template-thumbnail': _25;
        'template-select': _26;
        'spacer-component': _27;
        'ribbon-item': _28;
        'modal-content': _29;
        'flashcard-thumbnail': _30;
        'dimmed-background': _31;
        'card-input-field-view': _32;
    }
}